Added Discord badges and updated badges.fig
MikeCodesDotNET/ColoredBadges pull request #42
Opened 2020-07-21 21:39 UTC by fenix-hub

Hello,
I was looking for a Discord badge but didn't find any in the repository or in opened pull requests.
Hoping I'm not the blind one, I'd like to contribute adding a Discord badge with the following pull.

<img width="113" alt="discord@2x" src="https://user-images.githubusercontent.com/45271396/88109097-33134080-cbaa-11ea-8e2f-c044c774f100.png">
[badges.zip](https://github.com/MikeCodesDotNET/ColoredBadges/files/4956386/badges.zip)

The badge was made following this repository's directions and Discord's [branding](https://discord.com/new/branding).
*Icon background:* #7289DA (branding one)
*Badge background:* not changed
*Font:* not changed
*Icon:* customized inverting the original one, used in the Discord application itself

Files Added:
- discord.svg
- discord.png
- discord@2x.png
- discord@3x.png

Files Updated:
- badges.fig
- README.md

Let me know if there's something to be changed or improved :)

2020-07-28 07:20 UTC, swapnanildutta approved these changes

2021-09-14 15:17 UTC, swapnanildutta approved these changes

2022-09-01 15:06 UTC, anas-elgarhy approved these changes
This is beautiful ❤

2022-09-01 16:50 UTC, anas-elgarhy requested changes
Please update the `badges.fig` file and add the `oculus` and `supabase` and `nakama` and `vaadin` and `postgresSQL`  and `paypal`  to it

2023-10-06 17:45 UTC, Fasteroid commented
figma balls

2025-11-10 07:56 UTC, closed without merging